---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod-wrk-deployment
  labels:
    app: app-prod-wrk
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-prod-wrk
  template:
    metadata:
      labels:
        app: app-prod-wrk
        env: prod
    spec:
      containers:
        - name: app-prod-wrk
          image: rx9933/cardio-disease:2.1
          imagePullPolicy: Always
          command: ['python3', 'worker.py']
          env:
            - name: REDIS_IP
              value: '10.233.23.58'