version: "3"

services:
  redis-db:
    image: redis:7
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    user: "1000:1000"
    command: ["--save", "1", "1"]

  flask-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: alanarg3/cardio-diseases:1.0
    environment:
      - REDIS_IP=redis-db
    ports:
      - 5000:5000
    depends_on:
      - redis-db
    command: ["python3", "api.py"]

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    image: alanarg3/cardio-diseases:1.0
    depends_on:
      - redis-db
    command: ["python3", "worker.py"]

