---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-prod-redis-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi